spring.application.name=treat

spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.hbm2ddl.auto = update
spring.jpa.properties.hibernate.schema_update.unique_constraint_strategy = RECREATE_QUIETLY
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation = true

logging.level.root = WARN
server.port = 5050


spring.datasource.url = jdbc:postgresql://localhost:5432/tasty-treat
spring.datasource.username = postgres
spring.datasource.password = postgres

# JWT Configuration
jwt.secret=TastyTreatSuperSecretKeyThatIsAtLeast256BitsLong2024!
jwt.expiration=86400000